{
    "name": "Build",
    "on": {
      "push": {
          "branches": [ "main" ]
      },
      "pull_request": null,
    },
    "jobs": {
        "linux": {
            "name": "CI on x86_64",
            "runs-on": "ubuntu-latest",
            "strategy": {
                "fail-fast": false,
                "matrix": {
                    "name": [
                        "python-38",
                        "python-39",
                        "python-310",
                        "python-311",
                        "python-312",
                        "python-313",
                        "doc",
                        "doctest",
                        "sphinx",
                        "lint",
                        "pep8",
                        "codespell",
                    ],
                    "include": [
                        {
                            "name": "python-38",
                            "python": "3.8",
                            "toxenv": "py38",
                            "arch": "x64",
                        },
                        {
                            "name": "python-39",
                            "python": "3.9",
                            "toxenv": "py39",
                            "arch": "x64",
                        },
                        {
                            "name": "python-310",
                            "python": "3.10",
                            "toxenv": "py310",
                            "arch": "x64",
                        },
                        {
                            "name": "python-311",
                            "python": "3.11",
                            "toxenv": "py311",
                            "arch": "x64",
                        },
                        {
                            "name": "python-312",
                            "python": "3.12",
                            "toxenv": "py312",
                            "arch": "x64",
                        },
                        {
                            "name": "python-313",
                            "python": "3.13",
                            "toxenv": "py313",
                            "arch": "x64",
                        },
                        {
                            "name": "doc",
                            "python": "3.13",
                            "toxenv": "doc",
                            "arch": "x64",
                        },
                        {
                            "name": "doctest",
                            "python": "3.13",
                            "toxenv": "doctest",
                            "arch": "x64",
                        },
                        {
                            "name": "sphinx",
                            "python": "3.13",
                            "toxenv": "sphinx",
                            "arch": "x64",
                        },
                        {
                            "name": "lint",
                            "python": "3.13",
                            "toxenv": "lint",
                            "arch": "x64",
                        },
                        {
                            "name": "pep8",
                            "python": "3.13",
                            "toxenv": "pep8",
                            "arch": "x64",
                        },
                        {
                            "name": "codespell",
                            "python": "3.13",
                            "toxenv": "codespell",
                            "arch": "x64",
                        },
                    ],
                },
            },
            "steps": [
                { "uses": "actions/checkout@v4" },
                {
                    "uses": "actions/setup-python@v5",
                    "with": {
                        "python-version": "${{ matrix.python }}",
                        "architecture": "${{ matrix.arch }}"
                    },
                },
                { "run": "sudo apt-get update" },
                { "run": "sudo apt-get install cargo" },
                { "run": "pip --version" },
                { "run": "pip install tox" },
                { "run": "tox --version" },
                {
                    "env": {
                          "TOXENV": "${{matrix.toxenv}}"
                    },
                    "run": "tox",
                },
            ],
        },
    },
}
